### ISSUE TITLE
Account not exist

### ISSUE THREAD

**Issue by SergenBey** [MfaXyz/Crypto-Triangular-Arbitrage-Bot#8]
**When i try to start the bot exception: 200- "code":"230008","msg":"account not exist" error*
All the API information I entered is complete and correct.

 Go to '"python triarb_kucoin'
 See error

**Screenshots**
![accountnotexist](https://user-images.githubusercontent.com/114618571/193150202-7ad94467-08e6-44bd-b5e5-9af86ff24bf1.png)

**Desktop 
Windows 10

**Comment by MfaXyz** [comment]
@SergenBey Hello there!
It's because you don't write your account id instead of account_id.
you must get account list and then set your USDT account_id.

for example:
"USDT": float(user.get_account('sqdogh219830eg921oik1ib120')['available']),

Read the docs:
https://github.com/Kucoin/kucoin-python-sdk

**Comment by SergenBey** [comment]
ok but how can i find my USDT or BTC account_id ? 
Can you give a detailed link or explanation?
thx...

**Comment by MfaXyz** [comment]
@SergenBey Hello again!

user.get_account_list()
